# By Harsh H. Rajpurohit
name: vpn_basic_project
description: Flutter Android VPN based on OpenVPN Library.
publish_to: "none"

# App Version
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

# App dependencies
dependencies:
  change_app_package_name: ^1.1.0
  csv: ^5.1.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: ^4.6.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.0.0
  lottie: ^2.7.0
  rename: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  # Enabling material design
  uses-material-design: true

  # App assets
  assets:
    - assets/
    - assets/vpn/
    - assets/image/
    - assets/lottie/
    - assets/flags/
